### ISSUE TITLE
refactor(core): what is value

### ISSUE THREAD

**Issue by tremppu** [margarita-form/margarita-form#174]
For most cases what is value is pretty clear;
- If control should return an email address, then value is a string
- If control should return a person with name, phone and email, it probably should be an object (map)
- If control should return multiple emails, then its an array of strings

Strings, numbers, Booleans and objects (maps) and simple arrays are pretty clear but what is array can contain a person or company?
In the most common case value for that could be something like this:
```json
[
  {
    "name": "John Doe",
    "email": "john.doe@email.com",
    "phone": "+358 400 123456"
  },
  {
    "name": "Awesome Company",
    "email": "contact@awesome-company",
    "phone": "+358 400 123456"
  }
]
```
On the surface it seem ok but if Person and Company require different validations, it's impossible to tell programmatically which is which. To enable checking that we need to add some metadata like this:
```json
[
  {
    "_name": "person",
    "name": "John Doe",
    "email": "john.doe@email.com",
    "phone": "+358 400 123456"
  },
  {
    "_name": "company",
    "name": "Awesome Company",
    "email": "contact@awesome-company",
    "phone": "+358 400 123456"
  }
]
```
With `_name` Margarita form can differ that "Hey, this should validate Company, not a Person". 

That solution works when working with objects but what about array of strings, numbers and Booleans all mixed? Should Margarita Form support that as well? One solution could be the following:
```json
[
  {
    "_name": "email",
    "value": "john.doe@email.com"
  },
  {
    "_name": "phone",
    "value": "+358 400 123456"
  },
  {
    "_name": "address",
    "value": "Main Street 1, Helsinki, Finland"
  }
]
```
But if that is done, what is the real value of the "phone" control? Is it the phone number or the whole object? Either one that it will be, how does:
1. Validation work for self and for parent
2. Set value work for self and for parent

**Comment by jpaljakka** [comment]
So this would be the case right ? 
`[
  {
    "_type": "person",
    "name": "John Doe",
    "email": "john.doe@email.com",
    "phone": "+358 400 123456",
    "addresses": [
      {
        "_type": "address",
        "value": "123 Main St"
      },
      {
        "_type": "boolean",
        "value": true
      },
      {
        "_type": "number",
        "value": 42
      }
    ]
  },
]`

**Comment by tremppu** [comment]
> So this would be the case right ?
> 
> ```json
> [
>   {
>     "_type": "person",
>     "name": "John Doe",
>     "email": "john.doe@email.com",
>     "phone": "+358 400 123456",
>     "addresses": [
>       {
>         "_type": "address",
>         "value": "123 Main St"
>       },
>       {
>         "_type": "citizen",
>         "value": true
>       },
>       {
>         "_type": "id",
>         "value": 42
>       }
>     ]
>   },
> ]
> ```

Yes, only difference would be that instead of `_type` margarita form adds `_name`.

**Comment by tremppu** [comment]
After thinking and testing I have disabled support for cases where multiple different non group fields are present in array. This means that when parent grouping is array all of the children need to have grouping of "group".
